# Form implementation generated from reading ui file 'ui/Navigation.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.partnersBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.partnersBtn.setGeometry(QtCore.QRect(330, 150, 161, 41))
        self.partnersBtn.setObjectName("partnersBtn")
        self.salesBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.salesBtn.setGeometry(QtCore.QRect(330, 220, 161, 41))
        self.salesBtn.setObjectName("salesBtn")
        self.calcBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calcBtn.setGeometry(QtCore.QRect(330, 290, 161, 41))
        self.calcBtn.setObjectName("calcBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.partnersBtn.setText(_translate("MainWindow", "Партнеры"))
        self.salesBtn.setText(_translate("MainWindow", "Продажи"))
        self.calcBtn.setText(_translate("MainWindow", "Расчет"))
