# Form implementation generated from reading ui file 'ui/Partner.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(10, 10, 81, 24))
        self.backBtn.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.backBtn.setObjectName("backBtn")
        self.addPartnerBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addPartnerBtn.setGeometry(QtCore.QRect(610, 550, 161, 31))
        self.addPartnerBtn.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.addPartnerBtn.setObjectName("addPartnerBtn")

        self.partnersScrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.partnersScrollArea.setGeometry(QtCore.QRect(20, 40, 761, 501))
        self.partnersScrollArea.setWidgetResizable(True)
        self.partnersScrollArea.setObjectName("partnersScrollArea")

        self.verticalLayoutWidget = QtWidgets.QWidget()
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 761, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.partnersVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.partnersVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.partnersVerticalLayout.setObjectName("partnersVerticalLayout")
        self.partnersScrollArea.setWidget(self.verticalLayoutWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Партнеры"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
        self.addPartnerBtn.setText(_translate("MainWindow", "Добавить партнера"))
