# Form implementation generated from reading ui file 'ui/Sales.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 75, 24))
        self.backBtn.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.backBtn.setObjectName("backBtn")
        self.partnerComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.partnerComboBox.setGeometry(QtCore.QRect(530, 30, 251, 31))
        self.partnerComboBox.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.partnerComboBox.setObjectName("partnerComboBox")
        self.salesTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.salesTableWidget.setGeometry(QtCore.QRect(20, 70, 761, 511))
        self.salesTableWidget.setObjectName("salesTableWidget")
        self.salesTableWidget.setColumnCount(0)
        self.salesTableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
